### ISSUE TITLE
Do not use *Sync calls, use promises or callbacks

### ISSUE THREAD

**Issue by mcollina** [davidedantonio/create-fastify-app#1]
As titled: https://github.com/davidedantonio/create-fastify-app/blob/fc14cd87d76cd1d69672dd9c23bfc48269496d2c/lib/utils.js#L22.

(And in many other places)

**Comment by davidedantonio** [comment]
@mcollina Removed all Sync calls...I hope this is the right way to do it! 
Do you have any other suggestion? Or do you think that's okay?

**Comment by mcollina** [comment]
There is still https://github.com/davidedantonio/create-fastify-app/blob/master/lib/utils.js#L90.

Don't do https://github.com/davidedantonio/create-fastify-app/blob/master/lib/utils.js#L29-L62. remove `cb` and just use async functions. You are calling cb() multiple times in there.

process.exit() is a top-level concern, and should not really be in a utils file (https://github.com/davidedantonio/create-fastify-app/blob/master/lib/utils.js#L26).

Do not promisify manually (https://github.com/davidedantonio/create-fastify-app/blob/master/lib/fs.js), use https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_promisify_original.

**Comment by davidedantonio** [comment]
Thanks again for the suggestions! 🙏 

Do you think it is right to keep the fs.js file or move all the promisified functions to their respective files?

**Comment by mcollina** [comment]
I would remove it.

**Comment by davidedantonio** [comment]
I've removed the fs file utils except for `fileExists` function that I moved to the `utils.js` file. 
I need that this function return `true` or `false` value, and I don't think it's a good solution to rewrite the same function in all the files where I need it.

**Comment by mcollina** [comment]
Good work!
