### ISSUE TITLE
developer's documentation

### ISSUE THREAD

**Issue by sensorario** [davidedantonio/create-fastify-app#34]
May I ask you to complete readme file with test part? I've tried with `npm run unit` but test suite is not green. May I suggest to add commands or configuration required in readme file?

Thank you ^_^

**Comment by davidedantonio** [comment]
Let's take a look to the `.travis.yml` file. 
The unit test needs a set of server running, such as MySQL, MongoDB, Postgres... However I agree with you to write a better documentation for developers.

I would also like to do this task for the next major version.

**Comment by davidedantonio** [comment]
@sensorario added some info on how you need to run test in [README](https://github.com/davidedantonio/create-fastify-app/blob/develop/README.md#running-tests) file.

**Comment by davidedantonio** [comment]
@sensorario added `doker-compose.yml` in the root folder. Now you can type `docker-compose up -d` before running test.
