### ISSUE TITLE
autocompletion

### ISSUE THREAD

**Issue by sensorario** [davidedantonio/create-fastify-app#36]
May I add an autocompletion script for CFA? Are just these the commands?

  generate:project
  generate:service
  add:mysql
  add:mongo
  add:cors
  add:redis
  add:postgres

**Comment by davidedantonio** [comment]
I think this could be implemented for the next major version v2.0. What do you think? 
Checkout develop branche.

**Comment by sensorario** [comment]
I'll provide bash script ASAP

**Comment by davidedantonio** [comment]
Released v1.6.0
