### ISSUE TITLE
GET xxx /pov

### ISSUE THREAD

**Issue by xyz-mtl** [davidedantonio/create-fastify-app#82]
Adding POV and the call /pov returns :

> {"statusCode":500,"error":"Internal Server Error","message":"Unexpected identifier in /Users/xxxx/app/src/views/index.ejs while compiling ejs\n\nIf the above error is not helpful, you may want to try EJS-Lint:\nhttps://github.com/RyanZim/EJS-Lint\nOr, if you meant to create an async function, pass `async: true` as an option."}

**Comment by davidedantonio** [comment]
@xyz-mtl Now it's fixed
